### ISSUE TITLE
Disable multiple var declarations

### ISSUE THREAD

**Issue by filipmares** [ionutvmi/sublime-jsfmt#29]
I can't  figure out for the life of me how to turn off the multiple var declaration setting. 

Prevent:
```
var a = "1",
      b = "2";
```

From turning into:

```
var a = "1";
var b = "2";
```

**Comment by ionutvmi** [comment]
That is not included by default.
Check your settings file I think you added this plugin https://github.com/twolfson/esformatter-var-each
```js
{
	"options":
	{
		"plugins":
		[]
	}
}
```

**Comment by filipmares** [comment]
Odd. It looks like the jsfmt dependency includes that plugin https://github.com/rdio/jsfmt/blob/master/package.json

**Comment by ionutvmi** [comment]
can you share your configuration file ? I can try to reproduce it locally but it seems to work fine for me.

**Comment by filipmares** [comment]
I just removed and reinstalled it with same result. Here is my config file. I appreciated the help. 
```
{
  // autoformat on save
  "autoformat": true,

  // array of extensions for autoformat
  "extensions": ["jsx", "js", "sublime-settings"],

  // options for jsfmt
  "options": {
    "preset": "jquery",
    "indent": {
      "value": "    "
    },
    // plugins included
    "plugins": [
      "esformatter-jsx-ignore"
      // "esformatter-quotes",
      // "esformatter-semicolons",
      // "esformatter-braces",
      // "esformatter-dot-notation"
    ]
  },
  "options-JSON": {
    "plugins": [
      "esformatter-quotes"
    ],
    "quotes": {
      "type": "double"
    }
  },
  "node-path": "node",
  "alert-errors": true,
  "ignore-selection": false
}
```

**Comment by ionutvmi** [comment]
I just updated all the packages to the latest version and pushed a new release.  
It should get to you in a couple of hours.

This problem was caused by the fact that I was merging the settings recursively and it was merging the array of plugins instead of replacing it.
Since the var-each plugin is included by [default](https://github.com/rdio/jsfmt/blob/master/lib/defaultStyle.json#L3) in jsfmt 0.5.0 you were getting that formatting.

Please let me know if it's fixed.

**Comment by filipmares** [comment]
Thank you @ionutvmi! All good here.
